language: scala

scala:
  - 2.12.6

before_install:
  - openssl aes-256-cbc -K $encrypted_b8d1eb460fee_key -iv $encrypted_b8d1eb460fee_iv -in project/.gnupg/pubring.gpg.enc -out project/.gnupg/pubring.gpg -d
  - openssl aes-256-cbc -K $encrypted_b8d1eb460fee_key -iv $encrypted_b8d1eb460fee_iv -in project/.gnupg/secring.gpg.enc -out project/.gnupg/secring.gpg -d

script:
  - sbt coverage test 'it:testOnly -- timefactor 5' coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS publishSigned
  on:
    tags: true
