language: scala

scala:
  - 2.12.6

script:
  - sbt coverage test 'it:testOnly -- timefactor 5' coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS publish
  on:
    tags: true
