language: scala

scala:
  - 2.12.6

script:
  - sbt coverage test 'it:testOnly -- timefactor 5' coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - openssl aes-256-cbc -K $encrypted_e8a2d5297a89_key -iv $encrypted_e8a2d5297a89_iv
    -in project/.gnupg/keyring.tgz.enc -out project/.gnupg/keyring.tgz -d
  - tar zxf keyring.tgz

deploy:
  provider: script
  script: sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS publishSigned
  on:
    tags: true

